{{- $namespace := .Values.namespace }}
{{- range $name, $configMap := .Values.configMaps }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $name }}
  namespace: {{ $namespace }}
  labels:
    {{- range $key, $value := $configMap.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
  annotations:
    {{- range $key, $value := $configMap.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
data:
  api-metrics-dashboard.json: |
    {{- $.Files.Get "/dashboards/api-metrics-dashboard.json" | nindent 4 }}
  ec-metrics-dashboard.json: |
    {{- $.Files.Get "/dashboards/ec-metrics-dashboard.json" | nindent 4 }}
  node-exporter-full-1860.json: |
    {{- $.Files.Get "/dashboards/node-exporter-full-1860.json" | nindent 4 }}
{{- end }}
