apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Values.namespace }}
  labels:
    grafana_dashboard: "1"
  annotations:
    k8s-sidecar-target-directory: /tmp/dashboards/custom
data:
  {{- range $key, $filePath := .Values.configMaps.data }}
  {{ $key }}: |
    {{- $.Files.Get $filePath | nindent 4 }}
  {{- end }}
