apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMapName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- with .Values.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  {{- range $key, $filePath := .Values.configMaps.data }}
  {{ $key }}: |
    {{- $.Files.Get $filePath | nindent 4 }}
  {{- end }}
