{{- if .Values.certManager.staging.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: staging
spec:
  acme:
    email: {{ .Values.certManager.email }}
    server: {{ .Values.certManager.staging.server }}
    privateKeySecretRef:
      name: {{ .Values.certManager.staging.privateKeySecretRef }}
    solvers:
      - selector: {}
        http01:
          ingress:
            class: external-nginx
---
{{- end }}

{{- if .Values.certManager.production.enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: production
spec:
  acme:
    email: {{ .Values.certManager.email }}
    server: {{ .Values.certManager.production.server }}
    privateKeySecretRef:
      name: {{ .Values.certManager.production.privateKeySecretRef }}
    solvers:
      - selector: {}
        http01:
          ingress:
            class: external-nginx
---
{{- end }}
