{{- range .Values.certManager.issuers }}
{{- if .enabled }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
spec:
  acme:
    email: {{ $.Values.certManager.email }}
    server: {{ .server }}
    privateKeySecretRef:
      name: {{ .privateKeySecretRef }}
    solvers:
      - selector: {}
        http01:
          ingress:
            class: {{ .ingressClass }}
{{- end }}
{{- end }}
