# Default values for issuer-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

certManager:
  email: "valentino.giardino@southworks.com"
  
  issuers:
    - name: "staging"
      enabled: true
      server: "https://acme-staging-v02.api.letsencrypt.org/directory"
      privateKeySecretRef: "staging-cluster-issuer"
      ingressClass: "external-nginx"

    - name: "production"
      enabled: true
      server: "https://acme-v02.api.letsencrypt.org/directory"
      privateKeySecretRef: "production-cluster-issuer"
      ingressClass: "external-nginx"
