{
 "title": "Isolated Subscriptions API",
 "time": { "from": "now-3h", "to": "now" },
 "panels": [
  { "title": "Currently Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Currently Requests",
   "type": "bargauge",
   "description": "Number of Currently requests over.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(http_currently_requests)", "legendFormat": "__auto" },
    {}
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "description": "Total requests by method, endpoint and http status.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(http_requests_total) by (method, endpoint, http_status)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total requests per hour",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "increase(http_requests_total[1h])",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Success/Failure Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Success Requests Rate",
   "type": "timeseries",
   "description": "Proportion of successful applications in relation to the total",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{http_status=~\"2..\"}[1m])) / sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failure Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{http_status!~\"2..\"}[1m])) / sum(rate(http_requests_total[1m]))",
     "legendFormat": "__auto"
    },
    {}
   ]
  },
  {
   "title": "Total Time Out Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum(http_request_timeout_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "HTTP Errors 4xx",
   "type": "timeseries",
   "description": "Total of 4xx errors per minute",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(increase(http_request_failures_total{http_status=~\"4..\"}[2m])) by (method, endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Errors 5xx",
   "type": "timeseries",
   "description": "Total of 5xx errors per minute.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "sum(increase(http_request_failures_total{http_status=~\"5..\"}[2m])) by (method, endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Requests Rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Request Rates",
   "type": "timeseries",
   "description": "HTTP request rate per second, broken down by method and endpoint",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total[5m])) by (method, endpoint)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "description": "Average latency of HTTP requests for each method and endpoint, useful for monitoring overall API performance.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_latency_seconds_sum[2h]) / rate(http_request_latency_seconds_count[2h])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "description": "HTTP request latency in 50th, 90th and 99th percentiles to provide a detailed view of API performance.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_latency_histogram_seconds_bucket[2h])) by (le, method, endpoint))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_latency_histogram_seconds_bucket[2h])) by (le, method, endpoint))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_latency_histogram_seconds_bucket[2h])) by (le, method, endpoint))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}