{
 "title": "Event Consumer",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Subscriptions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total subscriptions created",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(event_type) (subscription_created_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total subscription creation failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(event_type) (subscription_creation_failure_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processing time based on number of processed messages",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(iteration_duration_seconds_sum) by (message_count) / sum(iteration_duration_seconds_count) by (message_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total subscriptions deleted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(event_type) (subscription_deleted_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total subscription deletion failures",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum by(event_type) (subscription_deletion_failure_total)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}